name: Xcode Build

on:
  push:
    branches:
      - main
    paths:
      - "**/*.swift"
  pull_request:
    paths:
      - "**/*.swift"
  workflow_dispatch:

jobs:
  xcodebuild:
    name: xcodebuild
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Build
        run: |
          xcodebuild \
            -project UnNatural.xcodeproj \
            -scheme UnNatural \
            -configuration Debug \
            -derivedDataPath "$RUNNER_TEMP/DerivedData" \
            CODE_SIGNING_ALLOWED=NO \
            build
